package ru.terraobjects.entity;
// Generated 07.04.2012 15:38:17 by Hibernate Tools 3.2.1.GA

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "property")
public class TOProperty implements java.io.Serializable {
    private Integer propId;
    private TOPropType propType;
    private String propDefvalue;
    private String propName;
    private Set<TOObjectTemplateProperty> objectTemplatePropses = new HashSet<TOObjectTemplateProperty>(0);
    private Set<TOObjectProperty> objectPropses = new HashSet<TOObjectProperty>(0);

    public TOProperty() {
    }

    public TOProperty(TOPropType propType, String propName) {
        this.propType = propType;
        this.propName = propName;
    }

    public TOProperty(TOPropType propType, String propDefvalue, String propName, Set<TOObjectTemplateProperty> objectTemplatePropses, Set<TOObjectProperty> objectPropses) {
        this.propType = propType;
        this.propDefvalue = propDefvalue;
        this.propName = propName;
        this.objectTemplatePropses = objectTemplatePropses;
        this.objectPropses = objectPropses;
    }

    @Id
    @Column(name = "prop_id", unique = true, nullable = false)
    public Integer getPropId() {
        return this.propId;
    }

    public void setPropId(Integer propId) {
        this.propId = propId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prop_type_id", nullable = false)
    public TOPropType getPropType() {
        return this.propType;
    }

    public void setPropType(TOPropType propType) {
        this.propType = propType;
    }

    @Column(name = "prop_defvalue", length = 20)
    public String getPropDefvalue() {
        return this.propDefvalue;
    }

    public void setPropDefvalue(String propDefvalue) {
        this.propDefvalue = propDefvalue;
    }

    @Column(name = "prop_name", nullable = false, length = 20)
    public String getPropName() {
        return this.propName;
    }

    public void setPropName(String propName) {
        this.propName = propName;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "property")
    public Set<TOObjectTemplateProperty> getObjectTemplatePropses() {
        return this.objectTemplatePropses;
    }

    public void setObjectTemplatePropses(Set<TOObjectTemplateProperty> objectTemplatePropses) {
        this.objectTemplatePropses = objectTemplatePropses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "property")
    public Set<TOObjectProperty> getObjectPropses() {
        return this.objectPropses;
    }

    public void setObjectPropses(Set<TOObjectProperty> objectPropses) {
        this.objectPropses = objectPropses;
    }
}
