package ru.terra.ejb.entity.dao;

/**
 *
 * @author terranz
 */
import java.sql.SQLException;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import net.sf.persist.*;
import ru.terra.ejb.entity.TOObject;
import ru.terra.ejb.entity.TOObjectProperty;
import ru.terra.ejb.entity.TOObjectTemplate;
import ru.terra.ejb.entity.TOObjectTemplateProperty;
import ru.terra.ejb.entity.TOProperty;

public class TOObjectsManager
{

    private Connection conn = null;
    private Persist persist = null;
    private static TOObjectsManager instance = new TOObjectsManager();

    private TOObjectsManager()
    {
	InitialContext ic = null;
	try
	{
	    ic = new InitialContext();
	} catch (NamingException ex)
	{
	    Logger.getLogger(TOObjectsManager.class.getName()).log(Level.SEVERE, null, ex);
	}
	DataSource ds = null;
	try
	{
	    ds = (DataSource) ic.lookup("topool");
	} catch (NamingException ex)
	{
	    Logger.getLogger(TOObjectsManager.class.getName()).log(Level.SEVERE, null, ex);
	}
	try
	{
	    conn = ds.getConnection();
	} catch (SQLException ex)
	{
	    Logger.getLogger(TOObjectsManager.class.getName()).log(Level.SEVERE, null, ex);
	}
	persist = new Persist(conn);
	persist.setUpdateAutoGeneratedKeys(true);
    }

    public static TOObjectsManager getInstance()
    {
	return instance;
    }

    public List getAllObjects()
    {
	return persist.readList(TOObject.class, DAOConsts.SELECT_ALL_OBJECTS);
    }

    public TOObject getObject(Integer id)
    {
	return persist.read(TOObject.class, DAOConsts.SELECT_OBJECT_BY_ID, id);
    }

    public TOObject createNewObject(Integer templateId)
    {
	TOObject newobj = new TOObject();
	newobj.setObjectCreatedAt(new Date());
	newobj.setObjectUpdatedAt(new Date());
	newobj.setObjectId(0);
	newobj.setObjectParentId(0);
	newobj.setObjectTemplateId(templateId);
	int added = 0;
	try
	{
	    //persist.insert(newobj);
	    PreparedStatement st = conn.prepareStatement("insert into object values (?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
	    st.setInt(1, 0);
	    st.setInt(2, 0);
	    st.setInt(3, templateId);
	    st.setDate(4, new java.sql.Date(newobj.getObjectCreatedAt().getTime()));
	    st.setDate(5, new java.sql.Date(newobj.getObjectUpdatedAt().getTime()));
	    st.execute();
	    ResultSet rs = st.getGeneratedKeys();
	    if (rs.last())
	    {
		added = rs.getInt(1);
	    }
	} catch (SQLException ex)
	{
	    Logger.getLogger(TOObjectsManager.class.getName()).log(Level.SEVERE, null, ex);
	}

	createDefaultPropsForObject(templateId, added);
	newobj.setObjectId(added);
	return newobj;
    }

    private void createDefaultPropsForObject(Integer templateId, Integer oid)
    {
	TOObjectTemplate template = persist.read(TOObjectTemplate.class, DAOConsts.SELECT_OBJECT_TEMPLATE_BY_ID, templateId);
	if (template == null)
	{
	    throw new RuntimeException("Template " + templateId + " not found!");
	}

	if (template.getParentObjectTemplateId() != null)
	{
	    createDefaultPropsForObject(templateId, oid);
	}

	List<TOObjectTemplateProperty> template_props = persist.readList(TOObjectTemplateProperty.class,
		DAOConsts.SELECT_OBJECT_TEMPLATE_PROPS_BY_TEMPLATE_ID, template.getObjectTemplateId());
	if (template_props.isEmpty())
	{
	    throw new RuntimeException("Template " + templateId + " does'nt contains properties!");
	}
	for (TOObjectTemplateProperty p : template_props)
	{
	    TOObjectProperty newprop = new TOObjectProperty();
	    newprop.setObjectId(oid);
	    newprop.setPropertyId(p.getPropertyId());
	    TOProperty prop = persist.read(TOProperty.class, DAOConsts.SELECT_PROPERTY_BY_ID, p.getPropertyId());
	    switch (prop.getPropTypeId())
	    {
		case 1: //String
		{
		    newprop.setStringVal(prop.getPropDefValue());
		}
		break;
		case 2: //Int
		{
		    newprop.setIntVal(Integer.valueOf(prop.getPropDefValue()));
		}
		break;
		case 3: //Float
		{
		    newprop.setFloatVal(Float.valueOf(prop.getPropDefValue()));
		}
		break;
		case 4: //Text
		{
		    newprop.setStringVal(prop.getPropDefValue());
		}
		break;
	    }
	    persist.insert(newprop);
	}
    }

    public TOObjectProperty getObjectProperty(Integer oid, Integer pid)
    {
	Object[] params = new Object[2];
	params[0] = oid;
	params[1] = pid;
	return persist.read(TOObjectProperty.class,
		DAOConsts.SELECT_OBJECT_PROPS_BY_OBJECT_ID_AND_PROP_ID, params);
    }

    public Object getPropertyValue(Integer oid, Integer pid)
    {
	TOObjectProperty objprop = getObjectProperty(oid, pid);
	TOProperty prop = persist.read(TOProperty.class,
		DAOConsts.SELECT_PROPERTY_BY_ID, objprop.getPropertyId());
	Object ret = new Object();
	switch (prop.getPropTypeId())
	{
	    case 1:
	    {
		ret = objprop.getStringVal();
	    }
	    break;
	    case 2:
	    {
		ret = objprop.getIntVal();
	    }
	    break;
	    case 3:
	    {
		ret = objprop.getFloatVal();
	    }
	    break;
	    case 4:
	    {
		ret = objprop.getTextVal();
	    }
	    break;
	}
	return ret;
    }

    //ставит значение в object_props нужному объекту
    public void setPropertyValue(Integer oid, Integer propid, Object value)
    {
	TOObjectProperty property = getObjectProperty(oid, propid);
	TOProperty prop = persist.read(TOProperty.class,
		DAOConsts.SELECT_PROPERTY_BY_ID, property.getPropertyId());
	switch (prop.getPropTypeId())
	{
	    case 1:
	    {
		property.setStringVal(String.valueOf(value));
	    }
	    break;
	    case 2:
	    {
		property.setIntVal(Integer.valueOf(String.valueOf(value)));
	    }
	    break;
	    case 3:
	    {
		property.setFloatVal(Float.valueOf(String.valueOf(value)));
	    }
	    break;
	    case 4:
	    {
		property.setStringVal(String.valueOf(value));
	    }
	    break;
	}
	persist.update(property);
    }
}
