package ru.terraobject.entity.dao;

/**
 *
 * @author terranz
 */
import java.util.List;
import java.sql.Connection;

import net.sf.persist.*;
import ru.terraobject.entity.TOObjectProperty;
import ru.terraobject.entity.TOProperty;
import ru.terraobject.entity.TOPropertyType;

public class TOPropertiesManager
{

    private Connection conn = null;
    private Persist persist = null;
    private static TOPropertiesManager instance = new TOPropertiesManager();

    private TOPropertiesManager()
    {
    }

    public void setConnection(Connection conn)
    {
	this.conn = conn;
	persist = new Persist(conn);
	persist.setUpdateAutoGeneratedKeys(true);
    }

    public static TOPropertiesManager getInstance()
    {
	return instance;
    }

    public List getPropertyTypes()
    {
	return persist.readList(TOPropertyType.class, DAOConsts.SELECT_ALL_PROP_TYPES);
    }

    public List getProperties()
    {
	return persist.readList(TOProperty.class, DAOConsts.SELECT_ALL_PROPERTIES);
    }

    public List getObjectProperties(Integer oid)
    {
	return persist.readList(TOObjectProperty.class, DAOConsts.SELECT_OBJECT_PROPS_BY_OBJECT_ID, oid);
    }

    public TOPropertyType getPropertyType(Integer propId)
    {
	TOPropertyType res = EntityCache.getInstance().getPropertyTypeFromCache(propId);
	if (res == null)
	{
	    res = persist.read(TOPropertyType.class, DAOConsts.SELECT_PROP_TYPE_BY_ID, propId);
	    EntityCache.getInstance().addPropertyTypeToCache(propId, res);
	}
	return res;
    }

    public TOObjectProperty getObjectProperty(Integer oId, Integer propId)
    {
	TOObjectProperty res = persist.read(TOObjectProperty.class, DAOConsts.SELECT_OBJECT_PROP_BY_OBJECT_ID_AND_PROP_ID, oId, propId);
	return res;
    }
}
