package ru.terraobjects.entity;
// Generated 07.04.2012 15:38:17 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObjectTemplateProps generated by hbm2java
 */
@Entity
@Table(name="object_template_props"
    ,catalog="terraobjects"
)
public class TOObjectTemplateProperty  implements java.io.Serializable {


     private Integer objectTemplatePropsId;
     private TOProperty property;
     private TOObjectTemplate objectTemplate;

    public TOObjectTemplateProperty() {
    }

    public TOObjectTemplateProperty(TOProperty property, TOObjectTemplate objectTemplate) {
       this.property = property;
       this.objectTemplate = objectTemplate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="object_template_props_id", unique=true, nullable=false)
    public Integer getObjectTemplatePropsId() {
        return this.objectTemplatePropsId;
    }
    
    public void setObjectTemplatePropsId(Integer objectTemplatePropsId) {
        this.objectTemplatePropsId = objectTemplatePropsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prop_id", nullable=false)
    public TOProperty getProperty() {
        return this.property;
    }
    
    public void setProperty(TOProperty property) {
        this.property = property;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="object_template_id", nullable=false)
    public TOObjectTemplate getObjectTemplate() {
        return this.objectTemplate;
    }
    
    public void setObjectTemplate(TOObjectTemplate objectTemplate) {
        this.objectTemplate = objectTemplate;
    }




}


