package ru.terraobjects.entity;
// Generated 07.04.2012 15:38:17 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObjectProps generated by hbm2java
 */
@Entity
@Table(name = "object_props", catalog = "terraobjects")
public class TOObjectProperty implements java.io.Serializable
{

    private TOObjectPropsId id;
    private TOObject object;
    private TOProperty property;
    private int propType;
    private Integer intval;
    private Float floatval;
    private String strval;
    private String textval;
    private Date dateval;
    private Integer listval;

    public TOObjectProperty()
    {
    }

    public TOObjectProperty(TOObjectPropsId id, TOObject object, TOProperty property, int propType)
    {
        this.id = id;
        this.object = object;
        this.property = property;
        this.propType = propType;
    }

    public TOObjectProperty(TOObjectPropsId id, TOObject object, TOProperty property, int propType, Integer intval, Float floatval, String strval, String textval, Date dateval, Integer listval)
    {
        this.id = id;
        this.object = object;
        this.property = property;
        this.propType = propType;
        this.intval = intval;
        this.floatval = floatval;
        this.strval = strval;
        this.textval = textval;
        this.dateval = dateval;
        this.listval = listval;
    }

    @EmbeddedId
    @AttributeOverrides(
    {
        @AttributeOverride(name = "objectPropsId", column =
        @Column(name = "object_props_id", nullable = false)),
        @AttributeOverride(name = "objectId", column =
        @Column(name = "object_id", nullable = false)),
        @AttributeOverride(name = "propId", column =
        @Column(name = "prop_id", nullable = false))
    })
    public TOObjectPropsId getId()
    {
        return this.id;
    }

    public void setId(TOObjectPropsId id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "object_id", nullable = false, insertable = false, updatable = false)
    public TOObject getObject()
    {
        return this.object;
    }

    public void setObject(TOObject object)
    {
        this.object = object;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prop_id", nullable = false, insertable = false, updatable = false)
    public TOProperty getProperty()
    {
        return this.property;
    }

    public void setProperty(TOProperty property)
    {
        this.property = property;
    }

    @Column(name = "prop_type", nullable = false)
    public int getPropType()
    {
        return this.propType;
    }

    public void setPropType(int propType)
    {
        this.propType = propType;
    }

    @Column(name = "intval")
    public Integer getIntval()
    {
        return this.intval;
    }

    public void setIntval(Integer intval)
    {
        this.intval = intval;
    }

    @Column(name = "floatval", precision = 12, scale = 0)
    public Float getFloatval()
    {
        return this.floatval;
    }

    public void setFloatval(Float floatval)
    {
        this.floatval = floatval;
    }

    @Column(name = "strval")
    public String getStrval()
    {
        return this.strval;
    }

    public void setStrval(String strval)
    {
        this.strval = strval;
    }

    @Column(name = "textval", length = 500)
    public String getTextval()
    {
        return this.textval;
    }

    public void setTextval(String textval)
    {
        this.textval = textval;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dateval", length = 19)
    public Date getDateval()
    {
        return this.dateval;
    }

    public void setDateval(Date dateval)
    {
        this.dateval = dateval;
    }

    @Column(name = "listval")
    public Integer getListval()
    {
        return this.listval;
    }

    public void setListval(Integer listval)
    {
        this.listval = listval;
    }
}
