package ru.terraobjects.entity;
// Generated 07.04.2012 15:38:17 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObjectPropList generated by hbm2java
 */
@Entity
@Table(name="object_prop_list"
    ,catalog="terraobjects"
)
public class TOObjectPropList  implements java.io.Serializable {


     private TOObjectPropListId id;
     private TOObject object;
     private int listId;
     private Integer position;

    public TOObjectPropList() {
    }

	
    public TOObjectPropList(TOObjectPropListId id, TOObject object, int listId) {
        this.id = id;
        this.object = object;
        this.listId = listId;
    }
    public TOObjectPropList(TOObjectPropListId id, TOObject object, int listId, Integer position) {
       this.id = id;
       this.object = object;
       this.listId = listId;
       this.position = position;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="objectPropertyListId", column=@Column(name="object_property_list_id", nullable=false) ), 
        @AttributeOverride(name="objectId", column=@Column(name="object_id", nullable=false) ) } )
    public TOObjectPropListId getId() {
        return this.id;
    }
    
    public void setId(TOObjectPropListId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="object_id", nullable=false, insertable=false, updatable=false)
    public TOObject getObject() {
        return this.object;
    }
    
    public void setObject(TOObject object) {
        this.object = object;
    }
    
    @Column(name="list_id", nullable=false)
    public int getListId() {
        return this.listId;
    }
    
    public void setListId(int listId) {
        this.listId = listId;
    }
    
    @Column(name="position")
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }




}


