package ru.terraobjects.entity;
// Generated 07.04.2012 15:38:17 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjectPropsId generated by hbm2java
 */
@Embeddable
public class TOObjectPropsId  implements java.io.Serializable {


     private int objectPropsId;
     private int objectId;
     private int propId;

    public TOObjectPropsId() {
    }

    public TOObjectPropsId(int objectPropsId, int objectId, int propId) {
       this.objectPropsId = objectPropsId;
       this.objectId = objectId;
       this.propId = propId;
    }
   

    @Column(name="object_props_id", nullable=false)
    public int getObjectPropsId() {
        return this.objectPropsId;
    }
    
    public void setObjectPropsId(int objectPropsId) {
        this.objectPropsId = objectPropsId;
    }

    @Column(name="object_id", nullable=false)
    public int getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(int objectId) {
        this.objectId = objectId;
    }

    @Column(name="prop_id", nullable=false)
    public int getPropId() {
        return this.propId;
    }
    
    public void setPropId(int propId) {
        this.propId = propId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TOObjectPropsId) ) return false;
		 TOObjectPropsId castOther = ( TOObjectPropsId ) other;
         
		 return (this.getObjectPropsId()==castOther.getObjectPropsId())
 && (this.getObjectId()==castOther.getObjectId())
 && (this.getPropId()==castOther.getPropId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getObjectPropsId();
         result = 37 * result + this.getObjectId();
         result = 37 * result + this.getPropId();
         return result;
   }   


}


