package ru.terraobjects.entity;
// Generated 07.04.2012 15:38:17 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ObjectTemplate generated by hbm2java
 */
@Entity
@Table(name="object_template"
    ,catalog="terraobjects"
)
public class TOObjectTemplate  implements java.io.Serializable {


     private Integer objectTemplateId;
     private String objectTemplateName;
     private Integer parentObjectTemplateId;
     private Set<TOObjectTemplateProperty> objectTemplatePropses = new HashSet<TOObjectTemplateProperty>(0);
     private Set<TOObject> objects = new HashSet<TOObject>(0);

    public TOObjectTemplate() {
    }

    public TOObjectTemplate(String objectTemplateName, Integer parentObjectTemplateId, Set<TOObjectTemplateProperty> objectTemplatePropses, Set<TOObject> objects) {
       this.objectTemplateName = objectTemplateName;
       this.parentObjectTemplateId = parentObjectTemplateId;
       this.objectTemplatePropses = objectTemplatePropses;
       this.objects = objects;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="object_template_id", unique=true, nullable=false)
    public Integer getObjectTemplateId() {
        return this.objectTemplateId;
    }
    
    public void setObjectTemplateId(Integer objectTemplateId) {
        this.objectTemplateId = objectTemplateId;
    }
    
    @Column(name="Object_Template_Name", length=20)
    public String getObjectTemplateName() {
        return this.objectTemplateName;
    }
    
    public void setObjectTemplateName(String objectTemplateName) {
        this.objectTemplateName = objectTemplateName;
    }
    
    @Column(name="parent_object_template_id")
    public Integer getParentObjectTemplateId() {
        return this.parentObjectTemplateId;
    }
    
    public void setParentObjectTemplateId(Integer parentObjectTemplateId) {
        this.parentObjectTemplateId = parentObjectTemplateId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="objectTemplate")
    public Set<TOObjectTemplateProperty> getObjectTemplatePropses() {
        return this.objectTemplatePropses;
    }
    
    public void setObjectTemplatePropses(Set<TOObjectTemplateProperty> objectTemplatePropses) {
        this.objectTemplatePropses = objectTemplatePropses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="objectTemplate")
    public Set<TOObject> getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set<TOObject> objects) {
        this.objects = objects;
    }




}


