package ru.terraobjects.entity;
// Generated 07.04.2012 15:38:17 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Object generated by hbm2java
 */
@Entity
@Table(name = "object", catalog = "terraobjects")
public class TOObject implements java.io.Serializable
{

    private Integer objectId;
    private TOObjectTemplate objectTemplate;
    private Integer parentObjectId;
    private Date objectCreatedAt;
    private Date objectUpdatedAt;
    private Set<TOObjectPropList> objectPropLists = new HashSet<TOObjectPropList>(0);
    private Set<TOObjectProperty> objectPropses = new HashSet<TOObjectProperty>(0);

    public TOObject()
    {
    }

    public TOObject(TOObjectTemplate objectTemplate, Integer parentObjectId, Date objectCreatedAt, Date objectUpdatedAt, Set<TOObjectPropList> objectPropLists, Set<TOObjectProperty> objectPropses)
    {
        this.objectTemplate = objectTemplate;
        this.parentObjectId = parentObjectId;
        this.objectCreatedAt = objectCreatedAt;
        this.objectUpdatedAt = objectUpdatedAt;
        this.objectPropLists = objectPropLists;
        this.objectPropses = objectPropses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "object_id", unique = true, nullable = false)
    public Integer getObjectId()
    {
        return this.objectId;
    }

    public void setObjectId(Integer objectId)
    {
        this.objectId = objectId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "object_template_id")
    public TOObjectTemplate getObjectTemplate()
    {
        return this.objectTemplate;
    }

    public void setObjectTemplate(TOObjectTemplate objectTemplate)
    {
        this.objectTemplate = objectTemplate;
    }

    @Column(name = "parent_object_id")
    public Integer getParentObjectId()
    {
        return this.parentObjectId;
    }

    public void setParentObjectId(Integer parentObjectId)
    {
        this.parentObjectId = parentObjectId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "object_created_at", length = 19)
    public Date getObjectCreatedAt()
    {
        return this.objectCreatedAt;
    }

    public void setObjectCreatedAt(Date objectCreatedAt)
    {
        this.objectCreatedAt = objectCreatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "object_updated_at", length = 19)
    public Date getObjectUpdatedAt()
    {
        return this.objectUpdatedAt;
    }

    public void setObjectUpdatedAt(Date objectUpdatedAt)
    {
        this.objectUpdatedAt = objectUpdatedAt;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "object")
    public Set<TOObjectPropList> getObjectPropLists()
    {
        return this.objectPropLists;
    }

    public void setObjectPropLists(Set<TOObjectPropList> objectPropLists)
    {
        this.objectPropLists = objectPropLists;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "object")
    public Set<TOObjectProperty> getObjectPropses()
    {
        return this.objectPropses;
    }

    public void setObjectPropses(Set<TOObjectProperty> objectPropses)
    {
        this.objectPropses = objectPropses;
    }
}
